### ISSUE TITLE
fuzzy search detection

### ISSUE THREAD

**Issue by rfwn** [TheKawasaki/persian-bad-words#1]
Implement a fuzzy search method, and return true if the text contains the swear or not, by a desired percentage.

For example, the word `sweeear` may not get detected, even though its actually a `swear`. You can get differences, and similarities between these two words. The Levenshtein distance between these is 2, as its not reliable for a definitive result, but it could get better with AI that manipulates the vowels and constants to see if they are actually same or not. ([Read more about Levenshtein distance here.](https://github.com/trekhleb/javascript-algorithms/tree/master/src/algorithms/string/levenshtein-distance))

If you feel lazy, I'll collaborate and hit a pull request for you.

**Comment by kaveh-dev** [comment]
hi there
I'll be happy to share your experiences!

**Comment by kaveh-dev** [comment]
I close this issue, if anyone is interested in this problem, feel free to submit a pull request!
